export * from "./AbsenMahasiswa"
export * from "./Dashboard"
export * from "./KalenderAkademik"
export * from "./MataKuliah"
export * from "./Materi"
export * from "./Profil"
export * from "./TugasMahasiswa"
export * from "./Dashboard/StudentClassDetail"