export * from "./Dashboard/DashboardDosenPage"
export * from "./Dashboard/DosenClassDetail"
export * from "./Profil/ProfilDosen"
export * from "./MataKuliah/MataKuliahDosen"
export * from "./Materi/MateriDosen"