export * from "./Dashboard/DashboardDosenPage"
export * from "./Dashboard/DosenClassDetail"
export * from "./Profil/ProfilDosen"
export * from "./MataKuliah/MataKuliahDosen"
export * from "./Materi/MateriDosen"
export * from "./Tugas/DosenTugas"
export * from "./Tugas/TugasDetail"
export * from "./Calendar/CalendarAcademic"