export * from "./Dashboard/DashboardAdminPage"
export * from "./Lecturer/LecturerTable"
export * from "./Class/AdminClass"
export * from "./Class/AdminClassDetail"
export * from "./Calendar/CalendarAcademic"